<a href="https://colab.research.google.com/github/MarioV3232/etl-data-pipeline2507452022/blob/main/notebooks/D_Empleados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

url="https://raw.githubusercontent.com/MarioV3232/etl-data-pipeline2507452022/refs/heads/main/data/raw/D_empleados.csv"
df = pd.read_csv(url)

df.head()

  id_empleado          nombre id_departamento fecha_ingreso
0       EM400    Marta Romero             D10    2023-09-12
1       EM401    José Ramírez             D15    2022-09-26
2       EM402   Miguel Romero             D10    2020-02-02
3       EM403     Elena Rivas             D99    2020-01-14
4       EM404  Fernando Rivas             D13    2022-12-25

In [ ]:
#Exploracion

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_empleado      136 non-null    object
 1   nombre           136 non-null    object
 2   id_departamento  129 non-null    object
 3   fecha_ingreso    132 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB

id_empleado        0
nombre             0
id_departamento    7
fecha_ingreso      4
dtype: int64

In [ ]:
# Limpiar Datos
df = df.drop_duplicates()
df = df.dropna()

In [ ]:
# Separar curated y rejects
df_rejects = df[df.isnull().any(axis=1)]
df_curated = df.dropna()
print(f"Curated: {len(df_curated)} | Rejects: {len(df_rejects)}")

Curated: 119 | Rejects: 0

In [ ]:
# Cargar a PostgreSQL
from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_seguros_30a9_user:Y6BGlJaThP4Pm8wnb3BmpmJ4AACL8Cuq@dpg-d6qu6u5m5p6s73ea8r60-a.oregon-postgres.render.com/etl_seguros_30a9")
df_curated.to_sql("empleados_curated", engine, if_exists="replace", index=False)
df_rejects.to_sql("empleados_rejects", engine, if_exists="replace", index=False)
print("Empleado cargado")

Empleado cargado

In [ ]:
# Guardar curated y rejects localmente en Colab
df_curated.to_csv("empleados_curated.csv", index=False)
df_rejects.to_csv("empleados_rejects.csv", index=False)