<a href="https://colab.research.google.com/github/MarioV3232/etl-data-pipeline2507452022/blob/main/notebooks/D_Salarios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

url="https://raw.githubusercontent.com/MarioV3232/etl-data-pipeline2507452022/refs/heads/main/data/raw/D_salarios.csv"
df = pd.read_csv(url)

df.head()

  id_salario id_empleado  salario    bono
0      S6000       EM432   586.98  281.04
1      S6001       EM454      NaN  473.55
2      S6002       EM406  1583.76  248.13
3      S6003       EM456   1647.0  190.26
4      S6004       EM525  2750.51   81.52

In [ ]:
#Exploracion

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_salario   136 non-null    object
 1   id_empleado  130 non-null    object
 2   salario      130 non-null    object
 3   bono         132 non-null    object
dtypes: object(4)
memory usage: 4.4+ KB

id_salario     0
id_empleado    6
salario        6
bono           4
dtype: int64

In [ ]:
# Limpiar Datos
df = df.drop_duplicates()
df = df.dropna()

In [ ]:
# Separar curated y rejects
df_rejects = df[df.isnull().any(axis=1)]
df_curated = df.dropna()
print(f"Curated: {len(df_curated)} | Rejects: {len(df_rejects)}")

Curated: 115 | Rejects: 0

In [ ]:
# Cargar a PostgreSQL
from sqlalchemy import create_engine

engine = create_engine("postgresql://etl_seguros_30a9_user:Y6BGlJaThP4Pm8wnb3BmpmJ4AACL8Cuq@dpg-d6qu6u5m5p6s73ea8r60-a.oregon-postgres.render.com/etl_seguros_30a9")
df_curated.to_sql("salario_curated", engine, if_exists="replace", index=False)
df_rejects.to_sql("salario_rejects", engine, if_exists="replace", index=False)
print("Salario cargado")

Salario cargado

In [ ]:
# Guardar curated y rejects localmente en Colab
df_curated.to_csv("salario_curated.csv", index=False)
df_rejects.to_csv("salario_rejects.csv", index=False)